### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by dy**
* Expose `intersects/<item>-<item>` API
* Update readme

### CODE REVIEW

**Comment by davidfig** [comment]
Why don't you like the src/ directory? It seem cleaner when opening the folder not to have so many .js files in the main directory.

**Comment by dy** [comment]
@davidfig from developer standpoint (ours) yes, I agree. But from the user and reader's standpoint having `require('intersects/circle-circle')` is more intuitive than `require('intersects/src/circle-circle')` - that is easy to remember (what other folders are there? `lib`? what level of nesting is in them?).

Having user's interests over implementors is important principle from [w3c](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies).

> users over authors over implementors over specifiers over theoretical purity

Also first-level entries look as if they are designed to be fully-fledged valid entries, not just some code internals.

**Comment by davidfig** [comment]
That makes sense. Thanks. It just makes it harder to track down the package.json file :) BTW: you have collaborator access. You can push your updates directly.

**Comment by dy** [comment]
@davidfig thanks!
I just want to make sure we are on the same page with that and there is no disagreement :)

**Pull request merged**
